[build]
  command = "npm install && npm run build"
  functions = "dist"

[dev]
    command = "node dist"
    port = 8010
    functionPort = "34567"
    targetPort = 8010
    autoLaunch = true

[[redirects]]
    from="/api"
    to="./netlify/functions/api"